FROM fedora:latest

RUN dnf update -y && dnf install -y python3 python3-pip gcc make curl bash && dnf clean all

RUN useradd --create-home cdeuser
WORKDIR /home/cdeuser

RUN mkdir /home/cdeuser/.cde /home/cdeuser/.cdp

RUN pip3 install --no-cache-dir jupyter \
  jupyterlab
RUN pip3 install numpy \
  pandas \
  matplotlib \
  scikit-learn

# Copy files and directories with ownership set to cdeuser
COPY --chown=cdeuser:cdeuser img /home/cdeuser/img
COPY --chown=cdeuser:cdeuser jupyterlab_qs /home/cdeuser/jupyterlab_qs
COPY --chown=cdeuser:cdeuser config.yaml /home/cdeuser/.cde/config.yaml
COPY --chown=cdeuser:cdeuser credentials /home/cdeuser/.cdp/credentials
COPY --chown=cdeuser:cdeuser cde /usr/bin/cde
COPY --chown=cdeuser:cdeuser cdeconnect.tar.gz /home/cdeuser/cdeconnect.tar.gz
COPY --chown=cdeuser:cdeuser pyspark-3.5.4.tar.gz /home/cdeuser/pyspark-3.5.4.tar.gz

USER root
RUN chown -R cdeuser:cdeuser /home/cdeuser &&\
    chmod -R u+rw /home/cdeuser
USER cdeuser

EXPOSE 8888

CMD ["bash", "-c", "jupyter-lab --ip='0.0.0.0' --port=8888 --no-browser"]
